USE employeedb;
-- STRING FUNCIONS
SELECT * FROM employees;

SELECT EMPLOYEE_ID, concat(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME FROM employees;

SELECT FIRST_NAME,upper(FIRST_NAME) AS UPPER_CASE, LAST_NAME, lower(LAST_NAME) AS LOWER_CASE FROM employees;

SELECT FIRST_NAME,LEFT(LAST_NAME,3) AS TRIMMED_NAME FROM employees;

SELECT RIGHT(FIRST_NAME,3),LEFT(LAST_NAME,3) AS TRIMMED_NAME FROM employees;

SELECT FIRST_NAME,length(FIRST_NAME) AS LEN_FIRST_NAME FROM employees;

SELECT * FROM employees
WHERE length(FIRST_NAME) <= 4;

SELECT FIRST_NAME, LAST_NAME, lower(concat(LEFT(FIRST_NAME,1),LAST_NAME,'@gmail.com')) AS EMAIL FROM employees;

-- NUMERICAL FUNCTION
SELECT ROUND(66.5,0);
SELECT 22/7;
SELECT ROUND(22/7,4);
SELECT ceil(54.1);
SELECT ceiling(45.6);
SELECT floor(44.999);
SELECT abs(-1);

-- Temporial Functions
SELECT NOW();

SELECT NOW(), date_format(now(),'%d-%m-%Y');
SELECT DATE(NOW());
SELECT YEAR(NOW());
SELECT TIME(NOW());
SELECT NOW(), date_format(now(),'%Y-%m-%d');

SELECT * FROM employees WHERE MONTH(HIRE_DATE) = 6;

SELECT date_add(now(), INTERVAL 28 DAY);
